import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'

export default function Home({images}) {

  React.useEffect(function mount() {
    function onLoad() {
      var elem = document.querySelector('.m-p-g');
      new MaterialPhotoGallery(elem);
    }

    window.addEventListener("load", onLoad);

    return function unMount() {
      window.removeEventListener("load", onLoad);
    };
  },[]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Studypaq frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Images Gallery
        </h1>

        <div className="m-p-g">
          <div className="m-p-g__thumbs" data-google-image-layout data-max-height="350">
            {
              images.map((item,index)=>{
                return (
                  <img src={item} data-full={item} className="m-p-g__thumbs-img" key={index}/>
                )
              })
            }
          </div>
          <div className="m-p-g__fullscreen"></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/manishjha5410"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Manish
        </a>
      </footer>
      <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/45226/material-photo-gallery.min.js'></script>
    </div>
  )
}


export async function getStaticProps() {
  const res = await fetch('https://www.reddit.com/r/images/top.json?limit=100&t=month')
  const posts = await res.json();

  let images = [];

  posts.data.children.forEach((el)=>{
    let item = el.data;

    if(item.domain === "i.redd.it"){
      images.push(item.url_overridden_by_dest);  
    } else {
      images.push(item.thumbnail);
    }
  })


  return {
    props: {
      images,
    },
  }
}
